name: CMOR-3.13.2
channels:
  - conda-forge
dependencies:
  - cmor=3.13.2
  - ipykernel
  - ipython
  - iris=3.13.1
  - jupyter_client
  - jupyter_core
  - pip=25.2
  - python=3.13.7
  - pip:
    - cmip7-data-request-api==1.4

